### ISSUE TITLE
suggestion box

### ISSUE THREAD

**Issue by kustomzone** [G1itchZero/zeronet-go#1]
- Is it perhaps better to list a stable proxy on the description (or readme)

https://zeronet.korso.win/g1itch.bit

- ZeroGo vs GoZero; 

Personally i think GoZero sounds/looks better. Also easier logo. (making) Did you consider both?

- Default port; 

Zeronet's roadmap includes app store, etc. If nofish decides to use 43111, is it better to set the default higher. eg 43210 (also easy to remember)

cheers, bot

**Comment by G1itchZero** [comment]
Hi there.
1. Good point. Didnt think about proxy.
2. I dont see any difference, i think, when it will be useful, ill start new discussion about naming.
3. Ok, 43210 - is good option.

Thanks for your ideas!
